host: "${host}"
username: "${user}"
password: "${password}"
tls:
  useTls: true
  certificate: "${cert}"
  certificatePassword: "${cert-pwd}"
opinions:
  web control admin: 1
  web control paco: 0.4
  cli: 0.9
messages:
  - topic: "my/test/topic/1" # Empty content
    interval: 12
    qos: 2
  - topic: "my/test/topic/2"  # With content
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a
     enim convallis enim ultricies ultrices. Vivamus quis mauris justo. Quisque sed 
     elementum leo, non lacinia augue."
    interval: 5
  - topic: "my/topic" # Only once
    content: ""
