services:
  hivemq:
    image: docker.io/hivemq/hivemq-ce
    container_name: hivemq
    environment:
      HIVEMQ_LOG_LEVEL: DEBUG
    volumes:
      - ./logs:/opt/hivemq/log
      - ./conf:/opt/hivemq/conf
      - ./extensions:/opt/hivemq/extensions
      - data:/opt/hivemq/data
    ports:
      - 127.0.0.1:1883:1883   # MQTT
      - 127.0.0.1:8883:8883   # MQTT + TLS
      - 127.0.0.1:8000:8000   # WS
volumes:
  data:
