services:
  hivemq:
    image: docker.io/hivemq/hivemq-ce
    container_name: hivemq
    environment:
      HIVEMQ_LOG_LEVEL: DEBUG
    volumes:
      - ./logs:/opt/hivemq/log
      - ./conf:/opt/hivemq/conf
      - ./extensions:/opt/hivemq/extensions
      - data:/opt/hivemq/data
    network_mode: host
    depends_on:
      - ldap

  ldap:
    image: lldap/lldap:stable
    container_name: ldap
    ports:
      # web front-end
      - 17170:17170
      - 127.0.0.1:3890:3890
    volumes:
      - ./ldap_data:/data
    environment:
      TZ: Europe/Madrid
      LLDAP_LDAP_BASE_DN: dc=example,dc=com
    env_file:
      - env

volumes:
  data:
