services:
  hivemq:
    image: docker.io/hivemq/hivemq-ce
    container_name: hivemq
    environment:
      HIVEMQ_LOG_LEVEL: DEBUG
    volumes:
      - ./logs:/opt/hivemq/log
      - ./conf:/opt/hivemq/conf
      - ./extensions:/opt/hivemq/extensions
      - hivemq-data:/opt/hivemq/data
    ports:
      - 1883:1883 # MQTT
      - 8883:8883 # MQTTS
      - 9010:9010 # JMX
    depends_on:
      - ldap

  ldap:
    image: lldap/lldap:stable
    container_name: ldap
    ports:
      - 17170:17170 # web front-end
    volumes:
      - ldap-data:/data
    environment:
      TZ: Europe/Madrid
      LLDAP_LDAP_BASE_DN: dc=example,dc=com

  web:
    build:
      context: ../web
      args:
        hostname: ${hostname:-example.com}
      tags:
        - web
    ports:
      - 80:80
      - 443:443
    depends_on:
      - hivemq
volumes:
  hivemq-data:
  ldap-data:
