host: "hivemq.lan"
username: "test"
password: "12345678"
#clientId: trust-cli
tls:
  useTls: true
  certificate: "/home/diego/Documents/TFG/client/src/main/resources/client-trust-store.jks"
  certificatePassword: "example"
opinions:
  web control admin: 1
messages:
  - topic: "my/test/topic/1" # Empty content
    interval: 12
    qos: 2
  - topic: "my/test/topic/2"  # With content
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a
     enim convallis enim ultricies ultrices. Vivamus quis mauris justo. Quisque sed 
     elementum leo, non lacinia augue."
    interval: 5
  - topic: "my/topic" # Only once
    content: ""
